### ISSUE TITLE
[Documentation]: Test if the CNF crashes when node drain and rescheduling occurs. All configuration should be stateless test should be separated to two cases

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/cnf-testsuite#1279]
**Describe the bug**
[Test](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-test-if-the-cnf-crashes-when-node-drain-and-rescheduling-occurs--all-configuration-should-be-stateless) if the CNF crashes when node drain and rescheduling occurs. All configuration should be stateless case tests node draining and stateless configuration. These should be two separate tests where the stateless configuration test can be optional for statefull applications, like DNS-es. 

**To Reproduce**

1. Go to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-test-if-the-cnf-crashes-when-node-drain-and-rescheduling-occurs--all-configuration-should-be-stateless
2. Read description
3. See error

**Expected behavior**
The test should be separate to two separate cases. 

**Screenshots**
N/A

**Device (please complete the following information):**

- All

**Comment by taylor** [comment]
@CsatariGergely this is probably just documentation issue. There are not two tests.  The single test is checking if a CNF comes up after a pod is rescheduled because of a node drain.

The configuration message is about a pod that expects data to exists on the host. If it is rescheduled it should be able to come back up and recreate / download data if needed.  That is of course only one issue that may cause the CNF to not come up properly after a pod is rescheduled.  The point is the CNF should continue to function after a pod is rescheduled. 

cc: @agentpoyo @denverwilliams I think the configuration message could be removed or expanded on for that test.  That test may be part of a documentation update though. Can y'all provide some more details and let me know if my thoughts above are correct.

**Comment by CsatariGergely** [comment]
Yes, I think the reference to configuration is misleading. This test does not test anything about the CNF configuration if I understood the explanation of @taylor correctly.

**Comment by wavell** [comment]
documentation has now been update:

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-test-if-the-cnf-crashes-when-node-drain-and-rescheduling-occurs--all-configuration-should-be-stateless

https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md#node-drain

https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md#test-if-the-cnf-crashes-when-node-drain-occurs-node_drain

**Comment by agentpoyo** [comment]
No AC required.
