### ISSUE TITLE
[Documentation] Document all tests & functions that only support the 'default' namespace

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-testsuite#1363]
**Affected Functions**: 
- All usage of the ```CNFManager.workload_resource_test(args, config) do |resource, container, initialized|``` function is broken as all of the resources returned will be reported as in the default namespace, even when the resource is in a different one. e.g ```nodeport_not_used resource: {kind: "Service", name: "coredns-coredns", namespace: "default"}```
- Any usage of ```KubectlClient::Get.resource(resource[:kind], resource[:name])``` e.g. ```KubectlClient::Get.resource command: kubectl get Service coredns-coredns -o json```
- Any usage of ```CNFManager.cnf_to_new_cluster(config, cluster.kubeconfig, offline)```
- Any usage of cnf_setup ```./cnf-testsuite -l info cnf_setup cnf-config=```
- Any usage of ```change_capacity(base_replicas, target_replicas, args, config, resource)```
- Any usage of ```def wait_for_scaling(resource, target_replica_count, args)```
- Any usage of ```KubectlClient::Get.resource_spec_labels(resource["kind"], resource["name"])```
- Any usage of ```ChaosTemplates::PodIoStress, ChaosTemplates::Cpu, ChaosTemplates::ContainerKill, ChaosTemplates::PodNetworkLatency, ChaosTemplates::PodNeworkCorruption, ChaosTemplates::PodNetworkDuplication, ChaosTemplates::DiskFill, ChaosTemplates::PodDelete, ChaosTemplates::PodMemoryHog, ChaosTemplates::NodeDrain, ChaosTemplates::PodDnsError,```

**Affected Tests**: 
Configuration
- nodeport_not_used
- hostport_not_used
- secrets_used
- immutable_configmap
- alpha_k8s_apis
- versioned_tag
Compatibility
- rolling_update
- rolling_downgrade
- rolling_version_change
- rollback
- increase_decrease_capacity
- increase_capacity
- decrease_capacity
State
- [x] shared_database
  - branch: `1286-microservice`
  - #1393
- [x] reasonable_image_size
  - branch: `1286-microservice`
  - #1393
- [x] single_process_type
  - branch: `1286-microservice`
  - #1393
- [x] service_discovery
  - branch: `1286-microservice`
  - #1393
- [ ] log_output
  - branch: `1286-observability`
- [ ] prometheus_traffic
  - branch: `1286-observability`
- [ ] routed_logs
  - branch: `1286-observability`
- [x] privileged
  - branch: `1286-security`
  - #1388
- [x] non_root_user
  - branch: `1286-security`
  - #1388
- liveness
- readiness
- pod_network_latency
- pod_network_corruption
- pod_network_duplication
- disk_fill
- pod_delete
- pod_memory_hog
- pod_io_stress
- pod_dns_error
- no_local_volume_configuration
- node_drain
- elastic_volumes
- database_persistence

Test categorises needing review
- [x] [configuration](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/configuration.cr)
- [x] [compatibility](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/compatibility.cr)
- [x] [microservice](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/microservice.cr)
- [x] [observability](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/observability.cr)
- [x] [reliability](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/reliability.cr)
- [x] [runtime](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/runtime.cr)
- [x] [security](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/security.cr)
- [x] [state](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/state.cr)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
This issue is for documentation

The followup issue for implementation would be #1286

**Comment by HashNuke** [comment]
# Notes from `microservice` category tests

Made the require changes in the `1286-microservice` branch. These fixes are yet to be tested.

## Review `shared_database`

#### Related to 1286
- `KubectlClient::Get.services` does not consider namespaces and assumes default namespace.
- `service_pod_ips` should include the namespace for each item in the array.
- Variable  `database_container_statuses` must include the namespace name. Because later on in the code we use crictl to inspect the container and also run netstat. `crictl` and  nsenter probably require namespaces.

#### Other issues

- `Mariadb.match` calls `ClusterTools.local_match_by_image_name` which matches against images used by the entire cluster and does not consider `EXCLUDE_NAMESPACES`
- `KubectlClient::Get.pods_by_digest`
	- Does not consider `EXCLUDE_NAMESPACES`
- Should filter services by namespaces after calls to `KubectlClient::Get.services` to exclude `EXCLUDE_NAMESPACES`

## Review `reasonable_image_size`
* `KubectlClient::Get.resource` should be passed a namespace argument.
* There is another call to the above helper to get info about secrets. That call should be passed the namespace of the resource.

## Review `single_process_type`
* `KubectlClient::Get.resource` and `KubectlClient::Get.resource_containers` should be passed the resource namespace.
* `KernelIntrospection::K8s.status_by_proc` needs to be passed namespace.
* Due to the above, the functions being called by the helper also need namespace to operate.
	* `KernelIntrospection::K8s::proc`

## Review `service_discovery`
* The call to `KubectlClient::Get.services` should be passed `all_namespaces: true`.

## Review `reasonable_startup_time`
Does not need updates

**Comment by HashNuke** [comment]
# Notes on `observability` tests

Made the require changes in the `1286-observability` branch. These fixes are yet to be tested.

## `log_output`
* [x] `KubectlClient.logs` should be passed namespace

## `prometheus_traffic`

#### Related to 1286

* [x] Call to `KubectlClient::Get.service_by_digest` needs to operate on all namespaces. Add an argument for `all_namespaces` to this helper.
* [x] `KubectlClient::Get.resource` should be passed resource namespace.
* [x] `KubectlClient::Get.pods_by_resource` should be passed resource namespace. Ideally based on the body of the helper function, we might as well parse the namespace from the resource spec.

#### Other issues
* [ ] There is a call to `DockerClient::K8s.local_digest_match` that does not respect `EXCLUDE_NAMESPACES` because the image IDs being passed are collected from all containers on the cluster.

## Review `open_metrics`
No updates required.

## Review `routed_logs`
* [x] `KubectlClient::Get.resource` should be passed namespace.
* [x] `KubectlClient::Get.pods_by_resource` should be passed namespace.

## Review `tracing`
No updates required.

**Comment by HashNuke** [comment]
# Notes on security tests

Working branch is at `1286-security`

## Review `privileged`
* [ ] `violation_list` is where the list of failures are stored. This should also store the namespace and resource (pod?) that the container belongs to.
* [ ] The list of containers that fail the test should be output along with the namespace name and resource name.

#### Additional impact area
* [ ] The config option `allowlist_helm_chart_container_names` should be passed the namespace of the container.

## Review `non_root_user`

#### Related to 1286
* [x] `KubectlClient::Get.resource` should be passed namespace argument.

#### Other issues
* [ ] Should respect `EXCLUDE_NAMESPACES`

## Kyverno tests that do not require changes
* `container_sock_mounts`
* `selinux_options`
* `external_ips`
* `sysctls`

## Kubescape tests with no changes required
* `hostpath_mounts`
* `immutable_file_systems`
* `privileged_containers`
* `network_policies`
* `non_root_containers`
* `host_pid_ipc_privileges`
* `ingress_egress_blocked`
* `resource_policies`
* `dangerous_capabilities`
* `insecure_capabilities`
* `linux_hardening`
* `service_account_mapping`
* `host_network`
* `application_credentials`
* `symlink_file_system`
* `privilege_escalation`

**Comment by taylor** [comment]
Estimate in points: 8
- @HashNuke 13
- @denverwilliams 8
- @agentpoyo 8
- @taylor 8
- @wavell 8
- @lixuna 8

**Comment by HashNuke** [comment]
# Notes on `state` tests

# State tests
## `no_local_volume_configuration`
* [ ] `KubectlClient::Get.pv_items_by_claim_name` should accept a namespace argument. The `KubectlClient::Get.pv` should also accept a namespace argument.
* [ ] `volume_hostpath_not_found` 

## `volume_hostpath_not_found`
No changes required

## `node_drain`
* [ ] Multiple calls to `KubectlClient::Get.resource_spec_labels` should be passed the namespace argument.
* [ ] kubectl command to get pods for a deployment should be passed the namespace argument
* [ ] Litmus experiment files should be checked for anything specific to namespace

## `elastic_volumes`
* [ ] `WorkloadResource.elastic?` should be passed namespace
* [ ] `KubectlClient::Get.resource` should be passed namespace

## `database_persistence`
* [ ] `KubectlClient::Get.resource` should be passed namespace
* [ ] `WorkloadResource.elastic?` should be passed namespace

**Comment by wavell** [comment]
documented and tested
