### ISSUE TITLE
[BUG] Mising files for results in the results directory for latest_tag and container_sock_mounts

### ISSUE THREAD

**Issue by daniel-wilmes** [cncf/cnf-testsuite#1794]
**Describe the bug**
When running cnf test suite (v0.41.2) for:
latest_tag
container_sock_mounts
We do not get a results file with any data. We use the results files to identify a test and sum the test score in our system. When running this bash command : grep -rnw 'results/' -e latest_tag we don't see any output that would suggest there is a tests. All other tests appear to produce output in the results directory with valid test names.

**To Reproduce**

1. Run latest_tag or container_sock_mounts individually
2. Check the results directory for the cnf test suite
3. run this command to see if there is a file with latest_tag or container_sock_mounts grep -rnw 'results/' -e latest_tag
4. No results with these tests

**Expected behavior**
Normally we have a file that looks like this for each test:

---
name: cnf testsuite
testsuite_version: <%= CnfTestSuite::VERSION %>
status:
points:
exit_code: 0
items: []

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]: Linux
- Distro [e.g. Ubuntu]: Ubuntu
- Version [e.g. 18.04]: 23.04
- Architecture [e.g. x86, arm] : x86
- Browser [e.g. chrome, safari]: chrome

**How will this be tested? aka Acceptance Criteria (optional)**

If the files in the results directory have files for:
latest_tag
container_sock_mounts

Once this issue is address how will the fix be verified?

Running the cnf test suite binary in our system.

**Comment by HashNuke** [comment]
Was able to reproduce this issue on the latest binary release (`v0.42.2`).
This issue is very likely happening because the test is crashing. Tests that crash are not added to the results file. This is another reported issue from what I remember. I'll find the other ticket and link to it here.

<img width="1384" alt="CleanShot 2023-05-09 at 18 07 09@2x" src="https://github.com/cncf/cnf-testsuite/assets/84005/12835672-980c-4d87-937f-fba61c8e59fa">

**Comment by HashNuke** [comment]
Tested multiple times and was not able to reproduce the test crash again. Pretty sure that is what is causing the results file to be empty.

<img width="1470" alt="CleanShot 2023-05-09 at 18 34 44@2x" src="https://github.com/cncf/cnf-testsuite/assets/84005/6880bdc4-16ab-4f6d-a809-5ffda2c660ee">

**Comment by HashNuke** [comment]
@daniel-wilmes Can you please run the individual tests with `LOG_LEVEL=debug` and share the test output?

**Comment by HashNuke** [comment]
If any test fails and is not included in the `results.yml`, then it might be the same as this [Issue-1334](https://github.com/cncf/cnf-testsuite/issues/1334). This is the issue I was referring to in an earlier comment on this ticket.

The test log will help confirm this issue.

**Comment by daniel-wilmes** [comment]
@HashNuke please see attached log
[output.txt](https://github.com/cncf/cnf-testsuite/files/11489724/output.txt)

**Comment by HashNuke** [comment]
The crash in the output confirmed my previous comment. Both the tests `latest_tag` and `container_sock_mounts` are crashing.

This is happening due to Kyverno policies not being found. I confirmed that the Kyverno policies do exist in the paths expected in the appropriate branch of `kyverno/policies` repo.

This was very likely due to the latest kyverno policies repo being downloaded prior to the fix for #1778 being made. The fix would have pinned the kyverno policies repo to a specific branch. That would resolve this issue.

Can you please attempt to re-run the testsuite after deleting the following paths?
```
# This is the kyverno binary path
/home/dwilmes/project/helm/certifications/cnf-testsuite/matrixx-dcp/target/test-classes/konstruxx/working/tests/runCNFTestSuite/tools/kyverno

# This is the kyverno policies path
/home/dwilmes/project/helm/certifications/cnf-testsuite/matrixx-dcp/target/test-classes/konstruxx/working/tests/runCNFTestSuite/tools/kyverno-policies
```

**Comment by lixuna** [comment]
Update: Please re-run v0.42.2 https://github.com/cncf/cnf-testsuite/releases/tag/v0.42.2 and let us know if this issue has been resolved

**Comment by daniel-wilmes** [comment]
This appears to be resolved.
