### ISSUE TITLE
[BUG] sig_term_handled fails github actions intermittently

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#1817]
**Describe the bug**
Sig_term is failing intermittently in the spec tests for github actions after merges are performed to the `main` branch. Rerunning failed job does not clear the error, usually a full re-run of all jobs is required once sig_term fails.

**To Reproduce**
Merge a PR to `main` and hope it fails.

**Expected behavior**
This should not fail intermittently.

**Failure Output from GH Actions**
```
Failures:

  1) Microservice 'sig_term_handled' should pass if SIGTERM is passed through to child processes by a supervisor (tini)
     Failure/Error: $?.success?.should be_true

       Expected: true
            got: false

     # spec/workload/microservice_spec.cr:273

Finished in 6:04 minutes
3 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec spec/workload/microservice_spec.cr:263 # Microservice 'sig_term_handled' should pass if SIGTERM is passed through to child processes by a supervisor (tini)
Error: Process completed with exit code 1.
```

**Comment by HashNuke** [comment]
Example links to failed jobs to help with debugging
* https://github.com/cncf/cnf-testsuite/actions/runs/6032090387/job/16366768905
* https://github.com/cncf/cnf-testsuite/actions/runs/6116762784/job/16602436473

**Comment by HashNuke** [comment]
The crash in the failed GitHub Actions jobs is due to the code in the `sig_term_handled` test looking for "ContainerID" for containers that are not running/available yet.

### Found a few other things about this test:
* The `sig_term_handled` test does not output pods & containers that failed the test or could not be checked (because not ready). Reported this as [#1825](https://github.com/cncf/cnf-testsuite/issues/1825)
* The `sig_term_handled` test does not wait for pods to be available. Any pod that has containers that aren't available yet will fail the test.
* The CNF that is used for the spec scenario uses Jenkins. The pod seems to take quite a while to start one of the containers that is responsible for config auto-reloads. I've disabled config auto-reloading in the sample CNF and as a result, the container in the CNF that was taking time to startup is now disabled too.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] When viewing github actions, I should not see sig_term test failures and tests should be passing.
