### ISSUE TITLE
[Feature] Cleanup installer messaging

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#745]
**Is your feature request related to a problem? Please describe.**
The installer provides too much information and the output is mixed so its harder to read what it actually did.

**Describe the solution you'd like**
Remove verbose messaging by default.  Could have an option to turn it on by passing an argument (eg. -v or verbose)

- Remove or limit curl download output.
- Remove extra single line message with `./cnf-testsuite` as the only item
- update text in path message to use uppercase PATH or don't have it in quotes
- adjust binary message to say it is a binary, eg. The cnf-testsuite binary has been successfully installed to: ~/.cnf-testsuite
- Possibly don't show shell type detection

**Describe alternatives you've considered**

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?
The output should only show the necessary messaging:
- PATH written
- binary installed

**Additional context**

<img width="1190" alt="Screen Shot 2021-04-28 at 3 23 12 PM" src="https://user-images.githubusercontent.com/26697/116468918-18f04800-a837-11eb-9ee7-5f49a39abae6.png">

**Comment by agentpoyo** [comment]
Acceptance Criteria:

This will need to be merged to `main` prior to testing due to how the curl installs the latest release.

- [ ]  Follow the [Quick Install from the README.md](https://github.com/cncf/cnf-testsuite#installation-and-usage) for the curl binary installation.
- [ ]  You will notice now that the curl command now has a `-s` in the docs: `source <(curl https://raw.githubusercontent.com/cncf/cnf-testsuite/main/curl_install.sh)`
- [ ]  You should see no download status and size messaging from the curl install.
- [ ]  If you are using BASH or ZSH, you should not see the shell type output while the install telling you that it was added to your PATH after successful installation.
- [ ]  If applicable, if using a non supported shell, it the output example of how to add cnf-testsuite to your PATH after successful installation.

**Comment by taylor** [comment]
@agentpoyo you can provide a link to the feature branch or paste the exact command in the ticket.  eg.
- https://github.com/cncf/cnf-testsuite/blob/feature/%23745_clean_up_binary_messaging/README.md#installation-and-usage
- Install the latest test suite binary: `source <(curl -s https://raw.githubusercontent.com/cncf/cnf-testsuite/main/curl_install.sh)`

**Comment by taylor** [comment]
@agentpoyo maybe you meant curl the installer from the branch?   That is ugly because of URL encoding:

```
https://raw.githubusercontent.com/cncf/cnf-testsuite/feature/%23745_clean_up_binary_messaging/curl_install.sh
```

**Comment by taylor** [comment]
The main issues seem correct in PR #779 for the branch.
The line showing `./cnf-testsuite` by itself is still there.  What is that for?

<img width="1161" alt="installation of cnf-testsuite using curl to the test branch. output shows ./cnf-testsuite on one line then an successful install message" src="https://user-images.githubusercontent.com/26697/118732391-e6b38400-b7ff-11eb-87ef-ed5a485464e8.png">

**Comment by taylor** [comment]
Maybe the line is coming from tar?  See https://github.com/cncf/cnf-testsuite/pull/779#discussion_r634799012

**Comment by agentpoyo** [comment]
> Maybe the line is coming from tar? See [#779 (comment)](https://github.com/cncf/cnf-testsuite/pull/779#discussion_r634799012)

Yeah, that was missed by me. And yes, there was no real easy way to do AC unless it's just merged into `main` branch to run through the actual INSTALL steps.

**Comment by taylor** [comment]
@agentpoyo that was a suggest edit, https://github.com/cncf/cnf-testsuite/pull/779#discussion_r634799012, but the PR is closed.  I created a new PR with the change.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/119006806-4d4ab600-b956-11eb-95f7-51813c0faf10.png)
