### ISSUE TITLE
[BUG] 0.11.0 expects for cnf-testsuite to be in the current working directory when not passing any arguments

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testsuite#746]
**Describe the bug**
After installing the v0.11.0 binary using the curl install directions (from the [main README](https://github.com/cncf/cnf-testsuite#to-give-it-a-try-immediately-you-can-use-these-quick-install-steps)) and trying to run it using `cnf-testsuite or ~/.cnf-testsuite/cnf-testsuite` it fails with a not found error message looking for `./cnf-testsuite`.  It is looking in current directory.

```taylor@cnfdev03:~/workspace/taylor$ cnf-testsuite 
--: 1: --: ./cnf-testsuite: not found

taylor@cnfdev03:~/workspace/taylor$ ~/.cnf-testsuite/cnf-testsuite 
--: 1: --: ./cnf-testsuite: not found
```

**To Reproduce**
1.  Uninstall your current version
2. Run the installer: `source <(curl https://raw.githubusercontent.com/cncf/cnf-testsuite/main/curl_install.sh)`
3. Run the command (no arguments needed): `cnf-testsuite` or `~/.cnf-testsuite`

**Expected behavior**
No error

Some short message?  What to run?

**Screenshots**

![image](https://user-images.githubusercontent.com/26697/116470949-b482b800-a839-11eb-83b3-e882554493d3.png)

**Device (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86 64bit

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unncesasray for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Comment by agentpoyo** [comment]
Acceptance Criteria:

 - [ ] `git clone https://github.com/cncf/cnf-testsuite.git` latest main branch as this bug was merged already.
 - [ ] Build the new binary `cd cnf-testsuite/; crystal build src/cnf-testsuite.cr --warnings none`
 - [ ] Copy the newly build binary into your path; if you've already downloaded the binary via curl, replace in your $HOME/.cnf-testsuite/ directory:  `cp cnf-testsuite $HOME/.cnf-testsuite/cnf-testsuite`
 - [ ] Verify the binary is in your path: `which cnf-testsuite` and it should display the location you copied to in previous step.
 - [ ] Verify the version is the latest `main` branch commit
 - [ ] Now run the cnf-testsuite from a random directory where the binary is not in the pwd without any options, e.g. /tmp: `cd /tmp; cnf-testsuite` and it should display the `help` message.
 - [ ] I can see a screenshot of the `help` message when no arguments are passed after running `cnf-testsuite`.

![image](https://user-images.githubusercontent.com/14348948/116633728-e53d1d00-a91f-11eb-80d1-3808f3401666.png)

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo what was the level of effort in points to resolve this issue? (ex. 0,1,2,3,5,8,13,21)

**Comment by agentpoyo** [comment]
2pts

**Comment by lixuna** [comment]
denver said 3, going with the higher estimate
