### ISSUE TITLE
[Feature] Add airgap support for OPA tests in github actions

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-testsuite#995]
**Describe the solution you'd like**
Need to add airgap support for OPA tests.

**Comment by denverwilliams** [comment]
@HashNuke The commits linked to this ticket look like they only added a github test that checks whether or not OPA works in an Airgapped environment. 

This ticket was for adding support to the OPA installation/test code so that OPA could be successfully installed and run in an airgapped environment. Unless there are other commits somewhere that added airgap support, it should't be able to run in airgapped mode and should be failing the test added in this PR?
